### PR TITLE
Typos and oversights

### PR DESCRIPTION
**Pull request by packy**
There are two changes in this request:
 + modify the behaviour of _datatype() so if the type passed into the function isn't one of the ones it needs to mangle, it passes the type through unchanged
 + Fix documentation: 'col_isnt_null' => 'col_not_null'. I didn't know why my test wasn't working, then I read the source. :)

### CODE REVIEW

**Comment by packy** [comment]
Thanks for the pull request... request. :)

This module is really useful!

**Comment by animalcarpet** [comment]
Thanks for this. I quite agree, it's incredibly useful. Can't believe the project has been languishing for so long without anyone having a go at extending it for the missing functionality.

**Comment by animalcarpet** [comment]
Reference my last message, I've added most of the functionality now that I think I need for my own purposes including a TAP test generation script autotap.sql which might be useful for people picking up a legacy project. The documentation is now way out of date which I need to fix before seeing if I can get this stuff merged into the main project.  Before I get onto that (and obviously I trying to find any excuse not to get down to it) did you see any glaring omissions in the coverage before I move onto the documentation?

**Comment by packy** [comment]
Not that I've noticed so far. I'm a newbie to MySQL, however: after 20+ years of Perl development where I had DBAs to deal with the db side of things, I've taken a job where the niche I settled into was writing MySQL stored procedures. So, when it came to testing those procedures, I immediately reached for TAP. :)

**Comment by animalcarpet** [comment]
It's somewhat ironic then that routines are the area I hadn't put too much work in to because it's a bit broken due a bug in the column definitions of the information_schema.routines table. If you haven't come up against the problem yet it has to do with having strict mode enabled when importing the functions and it affects MySQL 5.7 (5.5/5.6 seem to be OK). The bit I was most interested in was testing for changes in the routine definition.

**Pull request merged**
